// GLOBAL VARIABLES
export const GLOBAL_GRAPH_DATA  = 'GLOBAL_GRAPH_DATA';
export const GLOBAL_ARRAY_DATA  = 'GLOBAL_ARRAY_DATA';
export const GLOBAL_TASK_DATA   = 'GLOBAL_TASK_DATA';
export const GLOBAL_EXTERNAL_IP = 'GLOBAL_EXTERNAL_IP';
export const GLOBAL_CODA_HEALTH = 'GLOBAL_CODA_HEALTH';
export const GLOBAL_IMAGE_PATHS = "GLOBAL_IMAGE_PATHS";
export const GLOBAL_VIEW_LOG    = "GLOBAL_VIEW_LOG";

// JOB VARIABLES
export const JOB_JOB_SELECTED    = 'JOB_JOB_SELECTED';
export const JOB_JOB_SELECTED_ID = 'JOB_JOB_SELECTED_ID';
export const JOB_JOB_EXPANDED    = 'JOB_JOB_EXPANDED';
export const JOB_GRAPH_SELECTED  = 'JOB_GRAPH_SELECTED';
export const JOB_ARRAY_SELECTED  = 'JOB_ARRAY_SELECTED';
export const JOB_TASK_SELECTED   = 'JOB_TASK_SELECTED';

// MODAL VARIABLES
export const MODAL_CONFIRM_OBJ     = 'MODAL_CONFIRM_OBJ';
export const MODAL_TYPE            = 'MODAL_TYPE';
export const MODAL_FLAG            = 'MODAL_FLAG';
export const MODAL_CALLBACK        = 'MODAL_CALLBACK';
export const MODAL_HOSTS_OBJ       = 'MODAL_HOSTS_OBJ';
export const MODAL_VALUE           = 'MODAL_VALUE';
export const MODAL_LOCAL_EXCLUSIVE = 'MODAL_LOCAL_EXCLUSIVE';
export const MODAL_SELECTED_HOSTS  = 'MODAL_SELECTED_HOSTS';
