/**
 * GLOBAL VARIABLES
 */
export const GLOBAL_GRAPH_DATA = 'GLOBAL_GRAPH_DATA';
export const GLOBAL_ARRAY_DATA = 'GLOBAL_ARRAY_DATA';
export const GLOBAL_TASK_DATA = 'GLOBAL_TASK_DATA';
export const GLOBAL_EXTERNAL_IP = 'GLOBAL_EXTERNAL_IP';
export const GLOBAL_CODA_HEALTH = 'GLOBAL_CODA_HEALTH';
export const GLOBAL_IMAGE_PATHS = 'GLOBAL_IMAGE_PATHS';

/**
 * JOB VARIABLES
 */
 export const JOB_ROWS_SELECTED = 'JOB_ROWS_SELECTED';